# Generated by Django 5.0.2 on 2024-03-08 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('pic', models.ImageField(upload_to='img')),
                ('dis', models.TextField()),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
