# Generated by Django 5.0.2 on 2024-03-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_add_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_product',
        ),
    ]
