# Generated by Django 5.0.2 on 2024-03-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_add_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_products',
            new_name='Add_product',
        ),
    ]
