# Generated by Django 5.0.2 on 2024-04-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_order_product_id_remove_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='G_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
