# Generated by Django 5.0.2 on 2024-04-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_g_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='gram',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
