# Generated by Django 5.0.2 on 2024-04-05 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_add_product_gram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='add_to_cart',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user_id',
        ),
        migrations.CreateModel(
            name='sub_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categories')),
            ],
        ),
        migrations.DeleteModel(
            name='Add_product',
        ),
        migrations.DeleteModel(
            name='Add_to_cart',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
