# Generated by Django 5.0.2 on 2024-04-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_add_to_cart_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('offer', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('gram', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='img')),
                ('dis', models.TextField()),
                ('categories_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categories')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_categories')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
